# Generated by Django 2.2 on 2020-01-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='timezone',
            new_name='start_timezone',
        ),
        migrations.AddField(
            model_name='event',
            name='end_timezone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
