# Generated by Django 2.2 on 2020-02-07 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20200205_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('A', 'Attending'), ('D', 'Declined'), ('M', 'Maybe'), ('I', 'Invite pending')], default='A', max_length=1),
        ),
        migrations.CreateModel(
            name='EventInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='events.Event')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_invites', to=settings.AUTH_USER_MODEL)),
                ('invitee_attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='events.Attendance')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'invitee')},
            },
        ),
    ]
