# Generated by Django 2.2 on 2020-02-18 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200217_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='main_image_offset',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
