# Generated by Django 2.2.9 on 2020-02-21 13:38

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_main_image_offset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='main_image_offset',
        ),
        migrations.AddField(
            model_name='event',
            name='main_image',
            field=models.ImageField(null=True, upload_to=events.models.Event.get_upload_path),
        ),
        migrations.AddField(
            model_name='event',
            name='main_image_crop',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
