# Generated by Django 2.2 on 2020-02-26 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200221_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinvite',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
