# Generated by Django 2.2 on 2020-03-05 12:59

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20200305_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='main_image_crop',
            new_name='main_image_crop_points',
        ),
        migrations.AddField(
            model_name='event',
            name='main_image_cropped',
            field=models.ImageField(null=True, upload_to=events.models.Event.get_upload_path),
        ),
    ]
