# Generated by Django 2.2 on 2020-03-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20200318_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_guests_to_invite',
            field=models.BooleanField(default=True),
        ),
    ]
