# Generated by Django 2.2 on 2020-03-27 16:30

from django.db import migrations, models
import django.db.models.deletion
import events.models
import prism.utils.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_reminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('image', models.ImageField(upload_to=prism.utils.mixins.ImageHandlerMixin.get_upload_path)),
                ('cropped_image', models.ImageField(upload_to=prism.utils.mixins.ImageHandlerMixin.get_upload_path)),
                ('badge_color', models.CharField(max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=(prism.utils.mixins.ImageHandlerMixin, models.Model),
        ),
        migrations.RunSQL(
            sql="INSERT INTO events_eventcategory(name, image, cropped_image, badge_color, is_active) VALUES ('General', '', '', '#00FF00', TRUE);",
            reverse_sql=(),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_image',
            field=models.ImageField(null=True, upload_to=prism.utils.mixins.ImageHandlerMixin.get_upload_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_image_cropped',
            field=models.ImageField(null=True, upload_to=prism.utils.mixins.ImageHandlerMixin.get_upload_path),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='events.EventCategory'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='cropped_image',
            field=models.ImageField(upload_to=events.models.EventCategory.get_upload_path),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='image',
            field=models.ImageField(upload_to=events.models.EventCategory.get_upload_path),
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
