# Generated by Django 2.2 on 2020-03-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20200327_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='icon',
            field=models.ImageField(default='', upload_to='e_c'),
            preserve_default=False,
        ),
    ]
