# Generated by Django 2.2 on 2020-04-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_eventcomment'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            UPDATE events_event SET "end" = "start"::timestamp + interval '1 hour' WHERE "end" IS NULL;
            UPDATE events_event SET end_timezone = start_timezone WHERE end_timezone IS NULL;
            """,
            reverse_sql=(''),
        ),
    ]
