# Generated by Django 2.2 on 2020-04-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20200424_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='offset',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
