# Generated by Django 2.2 on 2020-05-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20200428_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='is_interest',
            field=models.BooleanField(default=False),
        ),
    ]
