# Generated by Django 2.2 on 2020-05-25 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_eventcategory_percent_of_regular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='liked',
            field=models.ManyToManyField(related_name='liked_events', through='events.EventLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
