# Generated by Django 2.2 on 2020-05-29 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20200525_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_from_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
