# Generated by Django 2.2 on 2020-06-22 13:54

from django.db import migrations, models
import prism.utils.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20200529_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=prism.utils.mixins.ImageHandlerMixin.get_upload_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_image_cropped',
            field=models.ImageField(blank=True, null=True, upload_to=prism.utils.mixins.ImageHandlerMixin.get_upload_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='provider',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
