# Generated by Django 2.2 on 2020-06-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20200622_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
